### ISSUE TITLE
UML Aufgabe 5

### ISSUE THREAD

**Issue by djsgirl** [sweIhm-ws2018-19/skillproject-fr-24#1]
Bearbeitung der Aufgabe 5 vom 1.Übungsblatt

**Comment by djsgirl** [comment]
Reviewer: ShinyKapador (Leonardo)

**Comment by djsgirl** [comment]
![aufgabe5](https://user-images.githubusercontent.com/37984862/47213285-ce0a3580-d39a-11e8-94cb-f0779211036d.PNG)

**Comment by ShinyKarpador** [comment]
Sieht ganz gut aus außer das bei dem Geschäftskonto ist der Firmenname abgeschnitten. Bei der Variable für die plz bei der Wohn- und Firmadresse fehlen die Gänsefüschen.

**Comment by djsgirl** [comment]
Bei den abgeschnittenen Sachen stimme ich dir zu aber man kann ja Zahlen sowohl als String als auch als Int speichern, deswegen ist es meiner Meinung nach richtig.
