### ISSUE TITLE
Anwendungsfalldiagramm Gesangstrainer

### ISSUE THREAD

**Issue by djsgirl** [sweIhm-ws2018-19/skillproject-fr-24#10]

**Comment by djsgirl** [comment]
So ich werde mich die Tage mal an das AnwendungsfallDiagramm machen.

**Comment by djsgirl** [comment]
![anwendungsfalldiagramm](https://user-images.githubusercontent.com/37984862/48019668-48c1a780-e134-11e8-819b-aebd783bf27c.JPG)

So sieht mein erster grober Umriss aus
Wäre cool wenn mir jemand sagen könnt ob des alle anwendungsfälle sind

**Comment by CharlyGeorge** [comment]
"Tipps Körperhaltung" und "Tipps anfragen" ist derselbe Anwendungsfall, oder?
Ich denke es fehlt noch "Wiederholung" (wenn User fragt "Wie bitte? Nochmal?" Oder Ähnliches). Sowie "Weiter" als Signalwort um Übungen zu überspringen und evtl noch "Shuffle", im Sinne von zufällige Wiedergabe der Tipps.
Hoffe das hilft. Wusst nicht wie du Anwendungsfälle genau definierst.

**Comment by djsgirl** [comment]
okay dann mach ich mal ne wiederholung rein und mach das mit den tipps in einen anwendungsfall
und ich würde die tipps immer zufällig wiedergeben.

**Comment by djsgirl** [comment]
![anwendungsfalldiagramm](https://user-images.githubusercontent.com/37984862/48256502-1bb11580-e410-11e8-9a77-be4441a79a59.JPG)

Hier habe ich dioe Änderungen umgesetz
Passt das jetzt?

**Comment by djsgirl** [comment]
![anwendungsfalldiagramm](https://user-images.githubusercontent.com/37984862/48259082-3470f980-e417-11e8-8a09-eca84ee2734e.JPG)

Wie besproen unsere Änderungen

**Comment by Klotzkopf** [comment]
ja passt

**Comment by djsgirl** [comment]
Kann ich es so lassen?

**Comment by CharlyGeorge** [comment]
Ja das passt.

**Comment by djsgirl** [comment]
Hat übrigens nicht so ganz gestimmt. Ich bearbeite es jetz mal nochmal.

**Comment by djsgirl** [comment]
![anwendungsfalldiagramm](https://user-images.githubusercontent.com/37984862/48311411-b724c080-e59f-11e8-847b-6864e4a8f907.JPG)

**Comment by CharlyGeorge** [comment]
Sind Anwendung abschalten, anschalten, Übung wiederholen, Übung überspringen keine Anwendungsfälle mehr?

**Comment by djsgirl** [comment]
Also an und Ausschalten ist so ne sache, des braucht man iwie ned, haben wir bei einem Beispiel von ihr a ned.
Und Überspringen tut man bei eurer Systemidee nicht, nur einmal dieses Aufwärmen ohne Beispiel machen, und da kontrolliert ja keiner ob du des wirkli8ch machst oder nicht.
