### ISSUE TITLE
Fachklassenmodell (Analyseklassenmodell) Gesangstrainer

### ISSUE THREAD

**Issue by djsgirl** [sweIhm-ws2018-19/skillproject-fr-24#11]

**Comment by ShinyKarpador** [comment]
![image](https://user-images.githubusercontent.com/43878914/48314299-d33c5800-e5c7-11e8-82ab-238121cc286b.png)
Ich hab jetzt mal den Prototyp des Klassendiagramm erstellt. Ich mir nicht sicher wie die einzelnen mp3 Dateien gespeichert werden, wie das dann im Klassendiagramm dargestellt wird und wie sie abgespielt werden bzw. wie das dargestellt wird.

**Comment by ShinyKarpador** [comment]
![image](https://user-images.githubusercontent.com/43878914/48315227-d4738200-e5d3-11e8-8e34-ed6bb61bc53c.png)
erste Änderungen
