### ISSUE TITLE
Begrüßung mit Vogellauten

### ISSUE THREAD

**Issue by Klotzkopf** [sweIhm-ws2018-19/skillproject-fr-24#13]
# User Story
Als User   möchte ich nach dem Öffnen des Alexa-Skills mit kurzem Vogelgezwitscher begrüßt werden und dann den Begrüßungstext hören.

# Akzeptanzkriterien
- kurzer   angenehmer Vogellaut
- angenehme Begrüßung durch Alexa

**Comment by Klotzkopf** [comment]
Ich habe mal irgendeinen Vogellaut von Amazon genommen. Ihr müsstet nur noch sagen, ob der passt oder hier antworten welchen sound ihr euch wünscht.

**Comment by Verena95** [comment]
Wo können wir die denn anhören?

**Comment by Verena95** [comment]
ich finde das neue super
