### ISSUE TITLE
Hilfe zu Koloraturen

### ISSUE THREAD

**Issue by Klotzkopf** [sweIhm-ws2018-19/skillproject-fr-24#16]
# User Story
Als Nutzer möchte ich den Alexa-Skill fragen können was Koloraturen sind, um zu wissen was ich trainiere.

# Akzeptanzkriterien
- Erklärung   auf Anfrage
- verständlicher Text von Alexa

**Comment by CharlyGeorge** [comment]
Koloraturen nennen wir bitte "Läufe", damit Alexa das richtig ausspricht und erkennt.

**Comment by djsgirl** [comment]
Ich schliesse dieses Issue wegen doppeltem vorhandensein.
