### ISSUE TITLE
Lektionen Läufe

### ISSUE THREAD

**Issue by Klotzkopf** [sweIhm-ws2018-19/skillproject-fr-24#17]
# User Story
Als Nutzer möchte ich mehrere Lektionen zu Koloraturen.

# Akzeptanzkriterien
- klare Aufnahmen der Koloraturen
- mind. 3 Lektionen

**Comment by CharlyGeorge** [comment]
Koloraturen nennen wir bitte "Läufe", damit Alexa das Wort richtig ausspricht und es erkennt.
