### ISSUE TITLE
UML Aufgabe 4

### ISSUE THREAD

**Issue by Hempfle** [sweIhm-ws2018-19/skillproject-fr-24#2]

**Comment by Hempfle** [comment]
Klotzkopf ist Reviewer

**Comment by Klotzkopf** [comment]
In Klasse Konto: String bezeichnunung muss auf private gestellt werden
In Klasse Adresse: der private String adresse zu strasse umbennenen, wie im UML Diag.
Sonst ok :ok_hand:

**Comment by Hempfle** [comment]
---- FULL SUCCESS :D ----
