### ISSUE TITLE
Speichern der letzten Lektion

### ISSUE THREAD

**Issue by Klotzkopf** [sweIhm-ws2018-19/skillproject-fr-24#20]
# User Story
Als Nutzer möchte ich meine zuletzt durchgeführte Lektion gespeichert bekommen und auswählen können, ob ich sie wiederholen mag, die nächste Lektion durchführe oder den Speicherpunkt verwerfe, um restliche Lektionen zu Ende zu bringen, wenn mal nicht genug Zeit für alle vorhanden war.

# Akzeptanzkriterien
- speichern der letzen Lektion
- wiederholen der letzen Lektion vom Speicherpunkt aus
- zur nächsten Lektion vom Speicherpunkt aus
- Speicherpunkt wird verworfen/überschrieben, bei keinen der beiden Auswahlen

**Comment by Verena95** [comment]
nicht benötigt, da Lektionen zufällig ausgewählt werden
