### ISSUE TITLE
Sind Signalworte wie "WEITER", "WIEDERHOLEN" möglich?

### ISSUE THREAD

**Issue by Klotzkopf** [sweIhm-ws2018-19/skillproject-fr-24#26]

**Comment by CharlyGeorge** [comment]
**Weitere Fragen zu dem Thema:**
Sind diese Anwendungsfälle "Wiederholen" und "Überspringen" während der gesamten Anwendung möglich? Denn der User soll immer die Möglichkeit haben "Wiederholen" und "Überspringen" zu sagen und Alexa weiß dann, dass sie den Anwendungsfall nochmal wiederholen bzw. überspringen muss.

Sind zu den Signalwörtern "Wiederholen" und "Überspringen" auch noch Synonyme möglich, die der User sagen kann? (Von uns dafür angedachte Synonyme findet ihr im Google Drive Excel Sheet)
