### ISSUE TITLE
Sprint 1, UML: Aktivitätsdiagramm

### ISSUE THREAD

**Issue by Klotzkopf** [sweIhm-ws2018-19/skillproject-fr-24#30]
Hab hier erstmal einen Vorschlag für ein Aktivitätsdiagramm. Bitte sagt Bescheid, falls euch etwas auffällt.

![sprint1_aktivitatsdiagramm](https://user-images.githubusercontent.com/43878785/48981806-86ce3d80-f0da-11e8-973c-26d693b43a9c.png)

**Comment by ShinyKarpador** [comment]
Ich denke es wäre nicht schlecht dem user die option zu geben, nach Intervallen oder Kolleraturen das jeweils andere zu trainieren oder nochmal das selbe. So hab ich mir das gedacht: 
![sprint1_aktivitatsdiagramm](https://user-images.githubusercontent.com/43878914/49026842-248b4080-f19f-11e8-9622-1932a406122f.png)

**Comment by Klotzkopf** [comment]
Ja macht Sinn. Dann passt das jetzt.
