### ISSUE TITLE
Alexa kann nicht auf Audiofiles auf AWS zugreifen

### ISSUE THREAD

**Issue by Klotzkopf** [sweIhm-ws2018-19/skillproject-fr-24#34]
Audiofiles können nicht auf AWS gehostet werden, da die mangelnden Accountrechte den Programmzugriff verweigern.

**Comment by CharlyGeorge** [comment]
Habt ihr eine Lösung/Alternative auf das Problem gefunden? Wie ist der Stand?

**Comment by Hempfle** [comment]
Issue ist resolved.
AWS kann als Host verwendet werden

**Comment by Hempfle** [comment]
Kann geschlossen werden
