### ISSUE TITLE
Testing gesamter Kommunikationsstrang

### ISSUE THREAD

**Issue by CharlyGeorge** [sweIhm-ws2018-19/skillproject-fr-24#35]
Bitte setzt die Anwendung bis 7.12. soweit um, **dass wir den gesamten Kommunikationsstrang von Anfang bis Ende testen können.**
Hier nochmal der Strang von GetStoryLine: https://app.invocable.com/projects/49111?version=dev

Login Daten von https://app.invocable.com/projects/49111?version=dev
Benutzername: verena.sager@web.de
Passwort: Songbird123

**Das passt übrigens auch zu dem von Frau Socher definierten 2. Sprint:** "Stellen Sie sicher, dass Ihr Skill getestet werden kann. Tragen Sie dazu alle Ihre Teammitglieder und Ihre Professorin bei mindestens einer funktionierenden Alexa Skills Console unter Settings->User Permissions ein. Der Amazon Account Ihrer Professorin ist 'gsocher@yahoo.com'."

Gibt es damit Probleme?

**Comment by CharlyGeorge** [comment]
Login Daten von https://app.invocable.com/projects/49111?version=dev
Benutzername: verena.sager@web.de 
Passwort: Songbird123

**Comment by Verena95** [comment]
Bitte unbedingt UNSER Kommunikation Design verwenden mit all unseren Alexa Variationen und Synonymen. Findet ihr entweder in getstoryline oder in unserem googlesheet: https://docs.google.com/spreadsheets/d/1jzvlJWedNnaljy0GcWBmrQH6ZI7LCB6V2j9LrRpllCc/edit#gid=1316617569

**Comment by Hempfle** [comment]
Wie in der Whatsapp Gruppe besprochen wird es von unserer Seite nicht möglich sein, die finale Fassung bis Donnerstag/Freitag fertigzustellen.
Der Grund dafür ist die hohe Rate an Abgaben und die Tatsache, dass 2 Tage nicht ausreichend sind um alle Features zu implementieren.
Zwar stimmt es, dass Testing zum Abschluss des Sprints nötig ist, jedoch ist es für mich unverständlich weshalb hierfür (von Freitag ausgehend) 7-8 Tage notwendig sein sollen.

Bis Montag könnten wir eine Fassung entwickeln welche die finale Fassung repräsentiert.
Mel meinte noch das ihr Standspeicherung (innerhalb einer Datenbank) wäre ein Zusatzaufwand der min. einen weiteren Tag brauchen würde.

**Comment by CharlyGeorge** [comment]
Das bedeutet Montag, den 10.12. muss die finale Version also unbedingt stehen.
Die 5 Tage fürs Testing müssen mindestens da sein, da uns allen beim Testen sicher noch Fehler auffallen, die wir bis zum 14.12. in der Review Runde bereinigt haben müssen.

**Comment by CharlyGeorge** [comment]
Ich freue mich auf die finale Version am Montag & aufs Testen und hoffe natürlich auch, dass dann nur wenig verbessert/verändert werden muss.

Wenn noch irgendwelche Unklarheiten zum Kommunikationsdesign sind, jederzeit hier oder am Freitag ansprechen.

**Comment by ShinyKarpador** [comment]
Wieso sind auf GetStoryLine keine Koloraturen sondern Läufe? Der Entscheidungsblock heißt Koloraturen oder Intervalle aber man kommt damit nur auf Intervalle oder Läufe. Sind Koloraturen das selbe wie Läufe?

Wieso ist auf der Excel Tabelle für die Synonyme zweimal eine Spalte für Intervalle?

**Comment by Verena95** [comment]
Da ihr meintet Alexa erkennt das Wort Koloraturen nicht haben wir es in Läufe geändert ist praktisch das selbe ja. 

Ist wohl ein ausversehen dass das doppelt ist. 

Die Erklärung soll abgefragt werden sobald die Frage auftaucht " willst du Läufe oder Intervalle üben" . Dies ist im Block " Entscheidung Läufe und Intervalle "  Wenn der User beide Begriffe nicht kennt sollte er nun zusätzlich die Möglichkeit haben, nicht nur nach Intervallen oder Läufen zu fragen, sondern auch nach beiden gleichzeitig.

**Comment by CharlyGeorge** [comment]
Ich wollte eben die Anwendung auf Alexa Developer Console testen.
Leider ist es nicht möglich den gesamten Kommunikationsstrang von Anfang bis Ende zu testen?! Alexa gibt auch noch keine Audiodateien wieder. Wir hatten doch gesagt, dass das bis heute stehen muss, damit wir mit dem Testing beginnen können?
