### ISSUE TITLE
Abschluss von Aussagen, wenn Fall zuvor eingetreten ist? 

### ISSUE THREAD

**Issue by Verena95** [sweIhm-ws2018-19/skillproject-fr-24#39]
z.B. ..".....Möchtest du nun weiter machen mit Läufen?"-> ( nur wenn Läufe davor noch nicht geübt wurden)  und ähnliche Fälle.

rot Markiert im doc.sheet unter Alexa Variationen.

**Comment by Klotzkopf** [comment]
Durch die Session Attribute, die man Alexa mitgeben kann ist dies möglich.
