### ISSUE TITLE
UML Blatt 2 Aufgabe 1

### ISSUE THREAD

**Issue by Hempfle** [sweIhm-ws2018-19/skillproject-fr-24#4]
(.______.)

**Comment by Hempfle** [comment]
Eine einfache Kamera-App auf einem Smartphone hat folgende Funktionen:
1. Foto aufnehmen
2. Videoaufnahme starten
3. Videoaufnahme beenden
4. Blitz einstellen (aus/ein/auto)
5. Fotoalbum ansehen

Stellen Sie die Funktionalität dieser Kamera in Form eines UML-Anwendungsfalldiagramms
dar.

**Comment by Hempfle** [comment]
STAND 26.10.2018 13:06


<?xml version="1.0"?>

-<mxfile type="device" editor="www.draw.io" version="9.3.0" userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36">

<diagram name="Page-1" id="ec5a7857-802a-24ec-eb73-143d177200b8">7Zpbj6M2FIB/DY+NMOb6mGR3W6mtutKo7fbRSRywCpiCmST762tzBxPCZIDJtDMPIzgxB/z53HxAgdvg/GOMIu9XesC+oqmHswI/KZpmaTb/LwSXXKBbWi5wY3LIRaAWPJHvuBCqhTQlB5y0BjJKfUaitnBPwxDvWUuG4pie2sOO1G/fNUIulgRPe+TL0j/JgXm51NasWv4TJq5X3hmYTv7LDu3/dmOahsX9FA0es7/85wCVuoqJJh460FNDBD8rcBtTyvKj4LzFvkBbYsuv+3Ll1+q5YxyyMRcUy/KM/LSY+u8JjotnY5eSB3/MSBymgb/eMxorcPOMY0Y4sV/QDvtfaUIYoSEfsqOM0YAP8MUPm4rHlvriuk81kVrH2ieuuJbRiEs9Fvj8BPBDmjKfhHhbLbPKhcUj82vx+eq0QQWT2yimAWbxhQ8pL9AL/oV9Aqc4P9WrDQuR11hos5Chwr7cSnPNmB8UmPuRQwm5hPvkEYafIrQX5yfuYW0qKIlyGkdyxlzr5kh8v+Qb0hBPA0kz2pAMmZGp90HSJ6CkS5S+UEaF0vQYYi/AoUSNK+DxQUz+Br+ZcNltXKaMC2g9uOwJaBm9tJC/SwOhOUyw9/jAoK2ubNj4W46fKfHb+IR95yJMwoTxwY+Hz9Dezt4sidcfPGG/K/esao0leNn9vAQsxGGJwgHj8PB41HSn66NgOWqORO1nFOAY/bCOIglUVmSIbJjVCG9jYmMzpDEBnNJ8h+oIblJrUQ3Xs2ww4JOKL98KXtnJX+JkZVQw8EGqkjsoeFmOYheX0+qn06BhDMCIsY8YeW7fsY9QcYevlPBnqUu6rn93q5CEpvEeF1c1S+KOIu1abVgqyqcsKcoWrJr2uDUED7eG+n9jDTulq6bOt4Zy7VXWDjy8KyI2mv+kYj+3WadJfZKt8kMWFpZqteAtWViA65WYRDN8jzDBojTlDHrdNsXu6v3x7Mu5s/HU5JwbY5bGMqUGh26To2qQNCI7jThpuDmgxMtKmDy2l40x+wXRXAb3yphc9UEK4Ba4MyYD44ai6WKy1pdXTRQIC/Vz+26e4TPjsJNK6LaGFGdzL/BQKsdnwr6VV/Hje5J8vkxKc7vbzPvgSvH2Suuxu/sHkz+3bWvQ0BwdAMu6z5YktZazEupM3VIz9aMsiy8OujSGRWJA8lrb0z5s76W2Z85ieyZ0Wv0ko52I+a/ArP8s/T5TtFRz9TLNi1pjX7f5wxoHrdGZxxoNdQWvW6PqrMwprBF0yqMbehe1RbmnP2SLJNz7qXgL+BjGCOYxxhF771cangGGwqAzTRQ07G4UvKF4UcOTt+iS4SzcZrH6l/q9tVmsjiI4X0kvNwbeSwv9LV889Lyp+d/n/6YfavOUntAZirncjycJurrZDbq3NC8adeXmU9djSSJm4+KE0ShikmWVX52ElI3w3vrTm9/yr0Zm9WrY8WrQ14ea690PlPtQIxJay+V6s1vuYqXHgfu96koJvUx607vN/y7y0f7VaX1V6W769AbljlX5Rv1E4oOSNWxdHNIge7VuZtF6F/Oj/qD8yK5jgE7zRh2ZELv473Kdj/bM4IbYkr3ZniVF6upgijQnSpHO0K5bMx5ndwxHfBd4T0yfascCrzj128T0aiVfvFGFXUVTxXR+Wn+3mw+vv42Gn/8F</diagram>

</mxfile>

**Comment by Hempfle** [comment]
STAND 26.10.2018 13:09

`<?xml version="1.0"?><mxfile userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36" version="9.3.0" editor="www.draw.io" type="device"><diagram id="ec5a7857-802a-24ec-eb73-143d177200b8" name="Page-1">7Zpbj6M2FIB/DY+NMOb6mGR3W6mtutKo7fbRSRywCpiCmST762tzBxPCZIDJtDMPIzgxB/z53HxAgdvg/GOMIu9XesC+oqmHswI/KZpmaTb/LwSXXKBbWi5wY3LIRaAWPJHvuBCqhTQlB5y0BjJKfUaitnBPwxDvWUuG4pie2sOO1G/fNUIulgRPe+TL0j/JgXm51NasWv4TJq5X3hmYTv7LDu3/dmOahsX9FA0es7/85wCVuoqJJh460FNDBD8rcBtTyvKj4LzFvkBbYsuv+3Ll1+q5YxyyMRcUy/KM/LSY+u8JjotnY5eSB3/MSBymgb/eMxorcPOMY0Y4sV/QDvtfaUIYoSEfsqOM0YAP8MUPm4rHlvriuk81kVrH2ieuuJbRiEs9Fvj8BPBDmjKfhHhbLbPKhcUj82vx+eq0QQWT2yimAWbxhQ8pL9AL/oV9Aqc4P9WrDQuR11hos5Chwr7cSnPNmB8UmPuRQwm5hPvkEYafIrQX5yfuYW0qKIlyGkdyxlzr5kh8v+Qb0hBPA0kz2pAMmZGp90HSJ6CkS5S+UEaF0vQYYi/AoUSNK+DxQUz+Br+ZcNltXKaMC2g9uOwJaBm9tJC/SwOhOUyw9/jAoK2ubNj4W46fKfHb+IR95yJMwoTxwY+Hz9Dezt4sidcfPGG/K/esao0leNn9vAQsxGGJwgHj8PB41HSn66NgOWqORO1nFOAY/bCOIglUVmSIbJjVCG9jYmMzpDEBnNJ8h+oIblJrUQ3Xs2ww4JOKL98KXtnJX+JkZVQw8EGqkjsoeFmOYheX0+qn06BhDMCIsY8YeW7fsY9QcYevlPBnqUu6rn93q5CEpvEeF1c1S+KOIu1abVgqyqcsKcoWrJr2uDUED7eG+n9jDTulq6bOt4Zy7VXWDjy8KyI2mv+kYj+3WadJfZKt8kMWFpZqteAtWViA65WYRDN8jzDBojTlDHrdNsXu6v3x7Mu5s/HU5JwbY5bGMqUGh26To2qQNCI7jThpuDmgxMtKmDy2l40x+wXRXAb3yphc9UEK4Ba4MyYD44ai6WKy1pdXTRQIC/Vz+26e4TPjsJNK6LaGFGdzL/BQKsdnwr6VV/Hje5J8vkxKc7vbzPvgSvH2Suuxu/sHkz+3bWvQ0BwdAMu6z5YktZazEupM3VIz9aMsiy8OujSGRWJA8lrb0z5s76W2Z85ieyZ0Wv0ko52I+a/ArP8s/T5TtFRz9TLNi1pjX7f5wxoHrdGZxxoNdQWvW6PqrMwprBF0yqMbehe1RbmnP2SLJNz7qXgL+BjGCOYxxhF771cangGGwqAzTRQ07G4UvKF4UcOTt+iS4SzcZrH6l/q9tVmsjiI4X0kvNwbeSwv9LV889Lyp+d/n/6YfavOUntAZirncjycJurrZDbq3NC8adeXmU9djSSJm4+KE0ShikmWVX52ElI3w3vrTm9/yr0Zm9WrY8WrQ14ea690PlPtQIxJay+V6s1vuYqXHgfu96koJvUx607vN/y7y0f7VaX1V6W769AbljlX5Rv1E4oOSNWxdHNIge7VuZtF6F/Oj/qD8yK5jgE7zRh2ZELv473Kdj/bM4IbYkr3ZniVF6upgijQnSpHO0K5bMx5ndwxHfBd4T0yfascCrzj128T0aiVfvFGFXUVTxXR+Wn+3mw+vv42Gn/8F</diagram></mxfile>`

**Comment by djsgirl** [comment]
Des kann man nicht anschauen

**Comment by Hempfle** [comment]
> 
> 
> Des kann man nicht anschauen

XML Files konnte man nicht anhängen. Spiele nachher den fertigen Stand ins Repository hoch. Es muss es noch einiges simplifiziert werden.

**Comment by djsgirl** [comment]
> 
> 
> > Des kann man nicht anschauen
> 
> XML Files konnte man nicht anhängen. Spiele nachher den fertigen Stand ins Repository hoch. Es muss es noch einiges simplifiziert werden.

Okay dann shcau ich mir des nachher an.

**Comment by Hempfle** [comment]
Finale PNG und XML sind im Repository hochgeladen

**Comment by Klotzkopf** [comment]
Video aufnehmen würde ich zu Videoaufnahme starten ändern. Ansonsten alles gut.

**Comment by Hempfle** [comment]
korrigiert
