### ISSUE TITLE
Aktivitätsdiagramm VS1

### ISSUE THREAD

**Issue by djsgirl** [sweIhm-ws2018-19/skillproject-fr-24#42]
Kann sich jemand mein Aktivitätsdiagramm anschauen? 
Hab mal ne 1 vs gemacht. 
https://github.com/sweIhm-ws2018-19/skillproject-fr-24/blob/master/UML/Sprint2/Aktivit%C3%A4tsdiagramm.JPG

**Comment by djsgirl** [comment]
https://github.com/sweIhm-ws2018-19/skillproject-fr-24/blob/master/UML/Sprint2/Aktivit%C3%A4tsdiagramm.JPG

**Comment by djsgirl** [comment]
Verdammt, sekunde
![aktivitatsdiagramm](https://user-images.githubusercontent.com/37984862/49700621-81e0b200-fbe1-11e8-9467-8e5590ab9196.JPG)

**Comment by CharlyGeorge** [comment]
Sieht gut aus. Aber der User soll nachdem er fertig ist mit "L" oder "I"  nicht gefragt werden, ob er Läufe oder Intervalle üben möchte, da er eins der beiden bereits abgeschlossen hat.
Das heißt nachdem "I" fertig ist muss Alexa fragen: "Möchtest du nun mit Läufen weiter machen?"
Und nachdem "L" fertig ist muss Alexa fragen: "Möchtest du nun mit Intervallen weiter machen?"

**Comment by CharlyGeorge** [comment]
Wenn der User daraufhin ja sagt, kommt er daraufhin entsprechend zu "I" oder "L".
Wenn der User nein sagt, soll Alexa reagieren mitl: "Super du hast das Ende deines Trainings für heute erreicht. Möchtest du zum Abschluss noch einen Tipp hören?"
Daraufhin kommt der User entweder zu Tipps oder zum "Ende"

**Comment by djsgirl** [comment]
ah okay, dann ändere ich des morgen so ab

**Comment by djsgirl** [comment]
![aktivitatsdiagramm](https://user-images.githubusercontent.com/37984862/49755166-7318fe80-fcb8-11e8-8c9e-9266a0f3d520.JPG)

**Comment by djsgirl** [comment]
So das ist die  geänderte Version2

**Comment by Klotzkopf** [comment]
ich würde es mir gerne ansehen, aber sobald ich heranzoome bleibt es leider verschwommen.

**Comment by djsgirl** [comment]
Hab des xml oben, also kannst da dann anschauen ;)
