### ISSUE TITLE
Alexa Antworten müssen funktionaler gewählt sein

### ISSUE THREAD

**Issue by Hempfle** [sweIhm-ws2018-19/skillproject-fr-24#43]
Aktuell werden in manchen Fällen gibt es noch einzelne Alexa-Antworten welche funktional ein Problem darstellen.
So sollte nach dem Abschluss des Läufe-Trainings keine JA-NEIN-FRAGE wie 
"Moechtest du nun weiter machen mit Laeufen? " geantwortet werden sondern eine Frage die speziell aufruft die nächste Aktivität zu äußern. Zum Beispiel: "Willst du erneut Läufe üben oder Intervalle trainieren?"

**Comment by Verena95** [comment]
ein ja -nein frage wird gestrichen bei Zwerchfell Intent : " Möchtest du ein Beispiel hören? " da Indes Zwerchfellbeispiel und kein Zwerchfellbeispiel raus fallen
