### ISSUE TITLE
Schreibfehler

### ISSUE THREAD

**Issue by Verena95** [sweIhm-ws2018-19/skillproject-fr-24#48]
Dein Gehoer wird trainiert, indem du Toene erkennst und anschließend nachsingst. Zu Beginn kann diese Ãœbung sehr schwierig erscheinen, da unser Gehoer vom Alltagslaerm ueberfordert sein kann. Goennne deinen Ohren eine Pause in der Stille und versuche im Alltag einzelne **Geraesche** bewusst herauszufiltern. Möchtest du jetzt an deiner Stimme arbeiten oder brauchst du noch einen weiteren Tipp?

-> Geräusche nicht Geraeche

**Comment by Klotzkopf** [comment]
Schreibfehler wurde behoben. Muss nur noch auf AWS hochgeladen werden.

**Comment by Verena95** [comment]
Durch die richtige Atemtechnik kannst du eine Ueberanstrengung der Stimme *vehindern*. Um diese zu ueben, lege deine Hand auf den Bauch. Achte darauf, dass deine Schultern entspannt sind und du dich nicht verkrampfst. Atme tief ein. Wenn sich deine Bauchdecke hebt, machst du es richtig. Brauchst du noch einen weiteren Tipp?
-> bei verhindern fehlt das R

**Comment by Verena95** [comment]
Die angeborene Tonreichweite eines jeden Menschens nennt man Ambitus. Durch Training kann dieser erweitert werden. Deine entspannte Stimmlage nennt man *Indiffernzlage*. Diese verwendest du, wenn du dich zum Beispiel mit andern unterhaeltst. Brauchst du noch einen weiteren Tipp?
-> Indifferenzlage.    fehlt ein E

**Comment by Klotzkopf** [comment]
korrigiert.
