### ISSUE TITLE
UML Blatt 2 Aufgabe 7

### ISSUE THREAD

**Issue by djsgirl** [sweIhm-ws2018-19/skillproject-fr-24#6]
Reviewer Leonardo

**Comment by djsgirl** [comment]
![aufgabe7](https://user-images.githubusercontent.com/37984862/47603260-26b87e80-d9ea-11e8-9ded-1290f6f6b8b6.JPG)

Aufgabe 7 hätte ich so gelöst, ob die Methoden pacage Protected oder public sind kann man nicht rauslesen, deswegen würde ich diese sachen nicht hinschreiben. Wie findet ihr das?

**Comment by ShinyKarpador** [comment]
Ja ich denke schon, dass das richtig ist. Ich war mir erst nicht sicher ob man vielleicht eine Verbindung für eine Assoziation zwischen den Klassen machen muss, aber aus dem Sequenzdiagramm kann man nicht entnehmen ob da eine besteht.

**Comment by djsgirl** [comment]
Ok Super, dann lassen wir es so.
