### ISSUE TITLE
UML Blatt 2 Aufgabe 6

### ISSUE THREAD

**Issue by Klotzkopf** [sweIhm-ws2018-19/skillproject-fr-24#7]
useless comment is useless

**Comment by Klotzkopf** [comment]
Hab meine Lösung gerade dem Repository hinzugefügt.

**Comment by Klotzkopf** [comment]
Mein Aktikivätsdiagramm sieht jetzt so aus:

![blatt_2_aufg_6](https://user-images.githubusercontent.com/43878785/47617635-76ba4280-dac9-11e8-941a-daa1f42a04d3.png)

**Comment by Hempfle** [comment]
Denke das Diagramm sollte passen. 
Meine Frage wäre nur wo 2a [ERWEITERUNG] "Artikelliste in Kundendatenbank speichern" vorkommt?
