### ISSUE TITLE
UML Blatt 2 Aufgabe 8

### ISSUE THREAD

**Issue by Klotzkopf** [sweIhm-ws2018-19/skillproject-fr-24#8]
![blatt2_aufg_8](https://user-images.githubusercontent.com/43878785/47617514-2ee6eb80-dac8-11e8-9967-4e0a8f9d10e2.png)

So sieht die vlt. Lösung erstmal aus.

**Comment by Hempfle** [comment]
Review:
1. Müssten die Verbindungen nicht Aggregationen sein ? (Verbindungen mit Rauten). 
Ein Dokument **beinhaltet** ja schließlich die Unterobjekte.

2. Da EinfacheGrafik von Grafik erbt fehlen hier noch die Attribute für "größe" und "position"

(3. Ist weniger ein Fehler sondern eher etwas was mich verwirrt: 
Warum hat die Klasse Text kein Attribut :O ?)

**Comment by Klotzkopf** [comment]
1. Bei den Aggregationen bin ich mir nicht sicher ob man sie mit einbinden muss, hab sie jetzt aber mal drin
2. Die vererbten Attribute wurden hinzugefügt.

![blatt2_aufg_8](https://user-images.githubusercontent.com/43878785/47774151-7d74cf80-dcec-11e8-8338-e60375547a6c.png)

Hoffe das passt jetzt
