### ISSUE TITLE
UML Blatt 2 Aufgabe 9

### ISSUE THREAD

**Issue by Hempfle** [sweIhm-ws2018-19/skillproject-fr-24#9]

**Comment by Hempfle** [comment]
Vorerstversion ist im Repository. Änderungen werden in den folgenden Tagen vorgenommen.

**Comment by Klotzkopf** [comment]
- Die Kästchen für die Objekte dürfen nicht abgerundet sein, da es Objekte sind.
- Der Aufbau ist name : Klasse  -> dokument1 und dokument2 müssen umbenannt werden und bei EinfacheGrafik die Nummern entfernen.
- Es fehlen die zurück gehenden Pfeile mit dem Rückgabewert bool bei allen Objekten, bis auf dok.1 denke ich.
Ansonsten passt es 👍

**Comment by Hempfle** [comment]
Korrekturen sind vorgenommen. 
Passt die Beschriftung der Returnpfeile ("true") ?
@Klotzkopf

**Comment by Klotzkopf** [comment]
Hätte die Beschriftung "bool" gewählt, da man nicht weiß welcher Wert denn die Funktion am Ende zurück gibt, aber denke true ist auch okay.
